window.TEMAS_PARADIGMAS = window.TEMAS_PARADIGMAS || [];
window.TEMAS_PARADIGMAS.push({
  id: "practica4",
  nombre: "Recursión con listas",
  tema: 4,
  resumenUrl: "resumen_p4.html",
  preguntas: [
    {
      concept: "Función es-prefijo?",
      conceptIndex: 1,
      question: "¿Qué devuelve (es-prefijo? '(a b) '(a b c d))?",
      options: ["#f", "#t", "#t si contiene"],
      correct: 1,
    },
    {
      concept: "Función es-prefijo?",
      conceptIndex: 1,
      question: "¿Qué devuelve (es-prefijo? '() '(a b c))?",
      options: ["#f", "#t", "Error"],
      correct: 1,
    },
    {
      concept: "Función inserta-ordenada",
      conceptIndex: 2,
      question: "¿Qué devuelve (inserta-ordenada 5 '(1 3 7 9))?",
      options: ["'(1 3 5 7 9)", "'(1 3 7 5 9)", "'(1 3 7 9 5)"],
      correct: 0,
    },
    {
      concept: "Función ordena",
      conceptIndex: 2,
      question: "¿Qué devuelve (ordena '(3 1 4 1 5))?",
      options: ["'(5 4 3 1 1)", "'(1 1 3 4 5)", "'(3 1 4 1 5)"],
      correct: 1,
    },
    {
      concept: "Función mueve-al-principio",
      conceptIndex: 3,
      question: "¿Qué devuelve (mueve-al-principio 'b '(a b c d))?",
      options: ["'(b a c d)", "'(b a b c d)", "'(a c d b)"],
      correct: 0,
    },
    {
      concept: "Función expande",
      conceptIndex: 4,
      question: "¿Qué devuelve (expande '(2 3))?",
      options: ["'((2) (3))", "'(2 3)", "'(2 2 2 3 3 3)"],
      correct: 2,
    },
    {
      concept: "Función expande-pareja",
      conceptIndex: 4,
      question: "¿Qué devuelve (expande-pareja '(2 . a))?",
      options: ["'(a a)", "'(2 a)", "'(a a a)"],
      correct: 0,
    },
    {
      concept: "Función elemento-central",
      conceptIndex: 5,
      question: "¿Qué devuelve (elemento-central '(a b c d e))?",
      options: ["'b", "'c", "3"],
      correct: 1,
    },
    {
      concept: "Lambda expressions",
      conceptIndex: 5,
      question: "¿Qué devuelve ((lambda (x y) (* x (+ 2 y))) (+ 2 3) 4)?",
      options: ["30", "32", "35"],
      correct: 0,
    },
    {
      concept: "Lambda expressions",
      conceptIndex: 5,
      question: "¿Qué devuelve ((lambda (x) (+ x (* x 2))) 5)?",
      options: ["15", "20", "25"],
      correct: 0,
    },
    {
      concept: "Higher-order functions",
      conceptIndex: 5,
      question: "Si (define doble (lambda (x) (* x 2))) y (define suma-2 (lambda (x) (+ x 2))), ¿qué devuelve (compose doble suma-2 3)?",
      options: ["10", "8", "11"],
      correct: 0,
    },
    {
      concept: "Recursión con listas",
      conceptIndex: 5,
      question: "¿Cuántas veces se llama recursivamente (ordena '(3 1 4)) si usa insertion sort?",
      options: ["2", "3", "4"],
      correct: 2,
    },
    {
      concept: "Card trick adivina",
      conceptIndex: 5,
      question: "El truco de cartas del ejercicio 6 reordena 3 montones y finalmente devuelve...",
      options: ["un monten ordenado", "la carta de arriba del último montón", "el montón central"],
      correct: 0,
    },
    {
      concept: "Recursión con listas",
      conceptIndex: 5,
      question: "¿Qué hace la función (reparte-tres lista)? Divide una lista en 3 montones...",
      options: ["por posición (0,3,6... / 1,4,7... / 2,5,8...)", "en partes iguales", "aleatorios"],
      correct: 0,
    },
    {
      concept: "Función map",
      conceptIndex: 5,
      question: "¿Qué devuelve (map (lambda (x) (* x 2)) '(1 2 3))?",
      options: ["'(2 4 6)", "'(1 2 3 1 2 3)", "Error"],
      correct: 0,
    },
  ],
});
