window.TEMAS_PARADIGMAS = window.TEMAS_PARADIGMAS || [];
window.TEMAS_PARADIGMAS.push({
  id: "practica3",
  nombre: "Recursión",
  tema: 3,
  resumenUrl: "resumen_p3.html",
  preguntas: [
    {
      concept: "Función minimo",
      conceptIndex: 1,
      question: "¿Qué devuelve (minimo '(1 8 6 4 3))?",
      options: ["3", "1", "8"],
      correct: 1,
    },
    {
      concept: "Función minimo",
      conceptIndex: 1,
      question: "¿Qué devuelve (minimo '(1 -1 3 -6 4))?",
      options: ["-1", "-6", "1"],
      correct: 1,
    },
    {
      concept: "Función minimo",
      conceptIndex: 1,
      question: "¿Qué devuelve (minimo '(5 5 5))?",
      options: ["0", "5", "15"],
      correct: 1,
    },
    {
      concept: "Función concatena",
      conceptIndex: 2,
      question: "¿Qué devuelve (concatena '(#\\H #\\o #\\l #\\a))?",
      options: ["\"hola\"", "\"Hola\"", "\"HOLA\""],
      correct: 1,
    },
    {
      concept: "Función concatena",
      conceptIndex: 2,
      question: "¿Qué devuelve (concatena '())?",
      options: ["\"\"", "'()", "Error"],
      correct: 0,
    },
    {
      concept: "Función contiene?",
      conceptIndex: 3,
      question: "¿Qué devuelve (contiene? '(algo 3 #\\A) 3)?",
      options: ["#f", "#t", "'(3)"],
      correct: 1,
    },
    {
      concept: "Función contiene?",
      conceptIndex: 3,
      question: "¿Qué devuelve (contiene? '() 5)?",
      options: ["#t", "#f", "Error"],
      correct: 1,
    },
    {
      concept: "Función str-contiene?",
      conceptIndex: 3,
      question: "¿Qué devuelve (str-contiene? \"Hola\" #\\o)?",
      options: ["#f", "#t", "2"],
      correct: 1,
    },
    {
      concept: "Función todos-iguales?",
      conceptIndex: 4,
      question: "¿Qué devuelve (todos-iguales? '(a a a a))?",
      options: ["#f", "#t", "4"],
      correct: 1,
    },
    {
      concept: "Función todos-iguales?",
      conceptIndex: 4,
      question: "¿Qué devuelve (todos-iguales? '(a a a b))?",
      options: ["#t", "#f", "Error"],
      correct: 1,
    },
    {
      concept: "Función todos-distintos?",
      conceptIndex: 5,
      question: "¿Qué devuelve (todos-distintos? '(a b c))?",
      options: ["#f", "#t", "'()"],
      correct: 1,
    },
    {
      concept: "Función todos-distintos?",
      conceptIndex: 5,
      question: "¿Qué devuelve (todos-distintos? '(a b c a))?",
      options: ["#t", "#f", "2"],
      correct: 1,
    },
    {
      concept: "Recursión básica",
      conceptIndex: 6,
      question: "¿Cuál es la lista que se pasa en la primera llamada recursiva a (minimo '(1 8 6 4 3))?",
      options: ["'(1 8 6 4)", "'(8 6 4 3)", "'(1 8 6)"],
      correct: 1,
    },
    {
      concept: "Recursión básica",
      conceptIndex: 6,
      question: "¿Qué devuelve la primera llamada recursiva en (minimo '(1 8 6 4 3))?",
      options: ["1", "3", "8"],
      correct: 1,
    },
    {
      concept: "Recursión básica",
      conceptIndex: 6,
      question: "¿Con qué devuelve (minimo '(1 8 6 4 3)) el resultado final?",
      options: ["(menor 3 1)", "(menor 1 3)", "(menor 8 6)"],
      correct: 1,
    },
  ],
});
